"""empty message

Revision ID: bfdb8e59422d
Revises: 678e395e529e
Create Date: 2022-11-04 11:49:31.337345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfdb8e59422d'
down_revision = '678e395e529e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('planet', sa.Column('moon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planet', 'moon', ['moon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.drop_column('planet', 'moon_id')
    op.drop_table('moon')
    # ### end Alembic commands ###
